-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 17:44:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/********************************************************
* This script creates the database named BookFinder 
*********************************************************/

DROP DATABASE IF EXISTS BookFinder;
CREATE DATABASE BookFinder;
USE BookFinder;


CREATE SCHEMA IF NOT EXISTS `BookFinder` DEFAULT CHARACTER SET utf8 ;
USE `BookFinder` ;

-- -----------------------------------------------------
-- Table `BookFinder`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookFinder`.`Authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(255) NOT NULL,
  `Website` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookFinder`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookFinder`.`Genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookFinder`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookFinder`.`Books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ISBN` INT NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `AuthorId` INT NOT NULL,
  `YearPublished` INT NOT NULL,
  `GenreId` INT NOT NULL,
  PRIMARY KEY (`id`, `ISBN`),
  INDEX `AuthorId_idx` (`AuthorId` ASC) VISIBLE,
  INDEX `GenreId_idx` (`GenreId` ASC) VISIBLE,
  CONSTRAINT `AuthorId`
    FOREIGN KEY (`AuthorId`)
    REFERENCES `BookFinder`.`Authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `GenreId`
    FOREIGN KEY (`GenreId`)
    REFERENCES `BookFinder`.`Genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookFinder`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookFinder`.`Addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `StreetAddr` VARCHAR(255) NOT NULL,
  `City` VARCHAR(255) NOT NULL,
  `State` VARCHAR(255) NOT NULL,
  `ZipCode` INT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookFinder`.`Bookstores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookFinder`.`Bookstores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `AddressId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `AddressId_idx` (`AddressId` ASC) VISIBLE,
  CONSTRAINT `AddressId`
    FOREIGN KEY (`AddressId`)
    REFERENCES `BookFinder`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookFinder`.`Libraries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookFinder`.`Libraries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BranchName` VARCHAR(255) NOT NULL,
  `AddressId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `AddressId_idx` (`AddressId` ASC) VISIBLE,
  CONSTRAINT `AddressId`
    FOREIGN KEY (`AddressId`)
    REFERENCES `BookFinder`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookFinder`.`StoreCopies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookFinder`.`StoreCopies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BookId` INT NOT NULL,
  `BookstoreId` INT NOT NULL,
  `Price` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id`, `BookId`),
  INDEX `BookId_idx` (`BookId` ASC) VISIBLE,
  INDEX `BookstoreId_idx` (`BookstoreId` ASC) VISIBLE,
  CONSTRAINT `BookId`
    FOREIGN KEY (`BookId`)
    REFERENCES `BookFinder`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BookstoreId`
    FOREIGN KEY (`BookstoreId`)
    REFERENCES `BookFinder`.`Bookstores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookFinder`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookFinder`.`Reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BookId` INT NOT NULL,
  `ReviewerName` VARCHAR(255) NOT NULL,
  `Stars` INT NOT NULL,
  `Review` VARCHAR(1000) NULL,
  `Date` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `BookId`),
  INDEX `BookId_idx` (`BookId` ASC) VISIBLE,
  CONSTRAINT `BookId`
    FOREIGN KEY (`BookId`)
    REFERENCES `BookFinder`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookFinder`.`LibraryCopies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookFinder`.`LibraryCopies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BookId` INT NOT NULL,
  `LibraryId` INT NOT NULL,
  `Available` TINYINT NOT NULL COMMENT 'Boolean -- Is this copy available?',
  PRIMARY KEY (`id`, `BookId`),
  INDEX `BookId_idx` (`BookId` ASC) VISIBLE,
  INDEX `LibraryId_idx` (`LibraryId` ASC) VISIBLE,
  CONSTRAINT `BookId`
    FOREIGN KEY (`BookId`)
    REFERENCES `BookFinder`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LibraryId`
    FOREIGN KEY (`LibraryId`)
    REFERENCES `BookFinder`.`Libraries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
